In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Step 2: Importing dataset**

In [56]:
dataset = pd.read_csv('Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [68]:
dataset.isnull().sum()/len(dataset)*100

Country       0.0
Age          10.0
Salary       10.0
Purchased     0.0
dtype: float64

In [61]:
p

Country          Age       Salary Purchased
0   France         44.0      72000.0        No
1    Spain         27.0      48000.0       Yes
2  Germany         30.0      54000.0        No
3    Spain         38.0      61000.0        No
4  Germany         40.0  222222222.0       Yes
5   France         35.0      58000.0       Yes
6    Spain  222222222.0      52000.0        No
7   France         48.0      79000.0       Yes
8  Germany         50.0      83000.0        No
9   France         37.0      67000.0       Yes

**Step 3: Handling the missing data**

In [7]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,3].values

In [12]:
from sklearn.impute import SimpleImputer

In [19]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [20]:
imputer = imputer.fit(X[:, 1:3])

In [53]:
X

array([[0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 

In [54]:
X[:, 1:3]

array([[1., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.]])

In [22]:
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

**Step 4: Encoding categorical data**

In [23]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [24]:
labelencoder_X = LabelEncoder()

In [25]:
X[:,0]

array(['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France',
       'Spain', 'France', 'Germany', 'France'], dtype=object)

In [26]:
X[:,0] = labelencoder_X.fit_transform(X[:,0])

In [27]:
X[:,0]

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=object)

**Step 5: Creating a dummy variable**

In [30]:
onehotencoder = OneHotEncoder()

In [31]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [33]:
X = onehotencoder.fit_transform(X).toarray()
X

array([[0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 

In [34]:
labelencoder_y = LabelEncoder()

In [35]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [36]:
y = labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

**Step 6: Splitting the datasets into training sets and Test sets**

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

**Step 7: Feature Scaling**

In [41]:
from sklearn.preprocessing import StandardScaler

In [42]:
sc_X = StandardScaler()

In [43]:
X_train

array([[1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 

In [44]:
X_train = sc_X.fit_transform(X_train)

In [45]:
X_train

array([[ 1.        , -1.        , -2.64575131,  2.64575131,  0.77459667,
        -0.77459667,  0.37796447, -0.37796447,  0.        ,  0.        ,
         0.37796447, -0.37796447,  0.37796447, -0.37796447,  0.37796447,
        -0.37796447,  0.37796447, -0.37796447, -2.64575131,  2.64575131,
         0.37796447, -0.37796447,  0.37796447, -0.37796447,  0.        ,
         0.        ,  0.37796447, -0.37796447,  0.37796447, -0.37796447,
         0.        ,  0.        ,  0.37796447, -0.37796447,  0.37796447,
        -0.37796447, -2.64575131,  2.64575131,  0.37796447, -0.37796447,
         0.37796447, -0.37796447,  0.37796447, -0.37796447,  0.        ,
         0.        ],
       [-1.        ,  1.        ,  0.37796447, -0.37796447,  0.77459667,
        -0.77459667,  0.37796447, -0.37796447,  0.        ,  0.        ,
         0.37796447, -0.37796447, -2.64575131,  2.64575131,  0.37796447,
        -0.37796447,  0.37796447, -0.37796447,  0.37796447, -0.37796447,
         0.37796447, -0.37796

In [46]:
X_test

array([[1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.]])

In [48]:
X_test = sc_X.transform(X_test)

In [49]:
X_test

array([[ 1.        , -1.        , -2.64575131,  2.64575131,  0.77459667,
        -0.77459667,  0.37796447, -0.37796447, -1.        ,  1.        ,
         0.37796447, -0.37796447,  0.37796447, -0.37796447,  0.37796447,
        -0.37796447,  0.37796447, -0.37796447,  0.37796447, -0.37796447,
         0.37796447, -0.37796447,  0.37796447, -0.37796447,  0.        ,
         0.        ,  0.37796447, -0.37796447,  0.37796447, -0.37796447,
        -1.        ,  1.        ,  0.37796447, -0.37796447,  0.37796447,
        -0.37796447,  0.37796447, -0.37796447,  0.37796447, -0.37796447,
         0.37796447, -0.37796447,  0.37796447, -0.37796447,  0.        ,
         0.        ],
       [ 1.        , -1.        , -2.64575131,  2.64575131,  0.77459667,
        -0.77459667,  0.37796447, -0.37796447,  0.        ,  0.        ,
         0.37796447, -0.37796447,  0.37796447, -0.37796447,  0.37796447,
        -0.37796447,  0.37796447, -0.37796447,  0.37796447, -0.37796447,
         0.37796447, -0.37796